title: MsquareCo
description: Your trusted partner for real estate in Dubai from Hyderabad.
baseurl: "/webapp" # very important for GitHub Pages if your repo is NOT username.github.io
url: "https://msquareco.github.io"

markdown: kramdown
theme: minima # or your custom theme if any
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  pages:
    output: true
plugins:
  - jekyll-sitemap
