title: MsquareCo
description: Strategic Real Estate Investments in Dubai
baseurl: ""
url: "https://msquareco.github.io"
markdown: kramdown
theme: minima
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
